### ISSUE TITLE
upgrade roles to use new tag format

### ISSUE THREAD

**Issue by iteratelance** [iterateco/ansible#22]
In the latest version of ansible 2.0 this format is no longer valid

``` yaml

---
- name: Configure ssh
  include: configure.yml tags=ssh,configure,configure:ssh
```

Instead the preferred format is as follows. 

``` yaml

---
- name: Configure ssh
  include: configure.yml 
  tags: ssh,configure,configure:ssh
```

I'm not sure if tags must be listed individually or if the comma separation still works.
