### ISSUE TITLE
create role for postgis

### ISSUE THREAD

**Issue by iteratelance** [iterateco/ansible#28]
We will want to add a new role for bionic that enable postgis support for postgres 9.6

You can see a sample of how we installed it for xenial https://github.com/iterateco/ansible/blob/master/roles/xenial/postgresql/tasks/install.yml

- name: Add postgis repo
  apt_repository:
    repo: ppa:ubuntugis/ubuntugis-unstable
    state: present
- name: Install postgresql-{{ postgresql_version }}-postgis-2.3
  apt:
    pkg: postgresql-{{ postgresql_version }}-postgis-2.3 
    state: present

**Comment by tanasin-vivitvorn** [comment]
OK let me check

**Comment by iteratelance** [comment]
@tanasin-vivitvorn I prematurely closed this PR, you can reopen it.  Why do you have with_items when you're not actually looping with it?  Plus postgis_package_version is not defined.
```yml
- name: Install postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
  apt:
    pkg: postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
    state: present
  with_items:
    - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}={{ postgis_package_version }}
```

I also received the following error messages. 
```bash
TASK [bionic/postgresql : List postgresql extension] *****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "psql -c \"SELECT * FROM pg_extension;\"", "delta": "0:00:00.287990", "end": "2018-10-02 23:18:29.945734", "msg": "non-zero return code", "rc": 2, "start": "2018-10-02 23:18:29.657744", "stderr": "psql: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?", "stderr_lines": ["psql: could not connect to server: No such file or directory", "\tIs the server running locally and accepting", "\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?"], "stdout": "", "stdout_lines": []}
```

```bash
TASK [bionic/postgresql : Enable postgis] ****************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'postgis_enabled' failed. The error was: error while evaluating conditional (postgis_enabled): 'postgis_enabled' is undefined\n\nThe error appears to have been in '/shared/roles/bionic/postgresql/tasks/install.yml': line 40, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable postgis\n  ^ here\n"}
	to retry, use: --limit @/shared/test-bionic.retry
```

**Comment by iteratelance** [comment]
To test you can create a test playbook as follows

test-bionic.yml
```yml
---
- name: Setup workstation
  hosts: localhost
  connection: local
  become: true
    
  pre_tasks:
    - debug: 
        var: ansible_env.HOME

    - name: Update apt
      apt: 
        update_cache: yes 
        cache_valid_time: 600

  tasks:
    # - include_role:
    #     name: bionic/bashprompt
    #   vars: 
    #     bashprompt_name: ansible
    # - include_role:
    #     name: bionic/boto3
    - include_role:
        name: bionic/common
    # - include_role:
    #     name: bionic/elasticsearch
    # - include_role:
    #     name: bionic/ganache-cli
    # - include_role:
    #     name: bionic/geth
    # - include_role:
    #     name: bionic/ipfs
    # - include_role:
    #     name: bionic/java
    # - include_role:
    #     name: bionic/nodejs
    # - include_role:
    #     name: bionic/packer
    # - include_role:
    #     name: bionic/pip
    # - include_role:
    #     name: bionic/pip3
    # - include_role:
    #     name: bionic/pm2
    - include_role:
        name: bionic/postgresql
    # - include_role:
    #     name: bionic/truffle
    # - include_role:
    #     name: bionic/ruby2.5
    # - include_role:
    #     name: bionic/yarn
    # - include_role:
    #     name: bionic/aws-cfn-bootstrap
    # - include_role:
    #     name: bionic/aws-cloudwatch
    # - include_role:
    #     name: bionic/aws-codedeploy
    # - include_role:
    #     name: bionic/aws-ssm
```
