### ISSUE TITLE
need ability to run post tasks on ami

### ISSUE THREAD

**Issue by iteratelance** [iterateco/ansible#4]
After creating an ami it's often desired to disable services etc.  These options should be configurable from ami.yml

```
    - name: Set init services to manual start
      shell: echo manual | sudo tee /etc/init/{{ item }}.override
      with_items:
        - mysql
    - name: Set update-rc.d services to start manually
      command: sudo update-rc.d -f {{ item }} remove
      with_items:
        - apache2
        - memcached
```
