### ISSUE TITLE
apache role clean up

### ISSUE THREAD

**Issue by iteratelance** [iterateco/ansible#7]
Template option should be removed from apache role and vhost.conf.j2 and stc.vhost.conf.j2 should be combined.  Eventually we may want the option to specify templates that exists outside of main framework.

Currently configure option requires passing in apache_sites_enabled: ['app', 'stc'].  Configuration will be based on tags so apache role will have to be modified such that parameters are passed in or we define which sites are mapped to which roles in our all.yml configuration.

For instance:

```
apache_sites_available:
  default:
    target_roles: ["app"]
    host: "{{env}}.{{app_domain_name}}"
```

The following would configure the virtual host above

```
configure.yml -e 'env=prod roles=app' --tags=apache 
```

This would not configure the virtual host above because default site is only targeted to 'app'

```
configure.yml -e 'env=prod roles=admin' --tags=apache 
```

Let's talk about this one before you being as crontabs might need the same flexibility.
